language: node_js
node_js:
  - "8"
install: npm ci
before_script: npm run transpile
script: npm run test
deploy: # to deploy run, `npm version [major|minor|patch]` && `git push`
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true # won't remove built files
  on:
    tags: true
